### ISSUE TITLE
 The getter 'iterator' was called on null.

### ISSUE THREAD

**Issue by vandan103** [Santos-Enoque/food_app_course#10]
NoSuchMethodError: The getter 'iterator' was called on null.
Receiver: null
Tried calling: iterator

in this function i got this error can anyone help me to solve this problem please ..as i know it related to state change function..

Future<void> _onStateChanged(FirebaseUser firebaseUser) async{
    if(firebaseUser == null){
      _status = Status.Unauthenticated;
      print("null user");
    }else{
      _user = firebaseUser;
      _status = Status.Authenticated;
      **_userModel = await _userServicse.getUserById(user.uid);**
    }
    notifyListeners();
  }
![Capture](https://user-images.githubusercontent.com/50577405/110237428-11f93780-7f62-11eb-81ee-f5c00fff2ec5.JPG)

**Comment by vandan103** [comment]
done

**Comment by mahenkvyas22** [comment]
vandan103 can you tell me how you  solved the adobe error

**Comment by vandan103** [comment]
yes i have linked this with my firebase database. and after that it linked with that and iterator was not called on null
please reach out to me on vandanpatel102@gmail.com

**Comment by vorishirne** [comment]
Hy can I get the firebase database. Is there way I can get the dummy data from somewhere. Or atleast the schema.
