### ISSUE TITLE
Accessing Orders Help Needed

### ISSUE THREAD

**Issue by TMoreMaker** [Santos-Enoque/food_app_course#4]
Hey @Santos-Enoque, I'm following the course but also making a few additions of my own to challenge myself, I'm having trouble with accessing the nested cart inside the orders list. I'm basically trying to unpack that Cart Map inside the List of orders so I can read that data

**Comment by Santos-Enoque** [comment]
Hey There, sorry for the late reply! I am glad it was sorted out!
